[package]
name = "md-viewer"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
env_logger = "0"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
